# Site settings

title: All I can be - A weblog by Dolf Andringa # Title of your site
email: dolfandringa@gmail.com # Your contant email
highlighter: rouge
destination: ../master/
keep_files: ['CNAME','.nojekyll','.git']

description: > # this means to ignore newlines until "baseurl:"
  This site is my personal showcase and outlet about what keeps me off the streets.
  It will mostly be about hacking, programming, GNU/Linux, but also about ecology, travel
  and science. I am a weird combination of an ecologist, hacker and ideologist.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://allican.be" # the base hostname & protocol for your site

slideshow:
    width: 600
    height: 400

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:       # Replace this with your Twitter username
github_username:      dolfandringa  # Replace this with your GitHub username
stackoverflow_userid: 867162
linkedin_username:    dolfandringa  # Replace this with your LinkedIn username
google_plus_username: +dolfandringa  # Replace this with your Google+ username
facebook_username:      # Replace this with your Facebook username
dribbble_username:      # Replace this with your Dribbble username

# Build settings
markdown: kramdown
permalink: blog/:year/:month/:day/:title:output_ext

collections:
    project:
        permalink: /:collection/:year/:month/:day/:title:output_ext
        output: true

tag_index_dir: "/archive/"
plugins:
      - jekyll-last-modified-at
      - jekyll-feed
